name: 'Setup Python Environment'
description: 'Checks out code, gets Python version, sets up Python, and installs dependencies'
inputs:
  poetry-version:
    description: 'The Poetry version to install'
    required: false
    default: '1.7.1'

runs:
  using: 'composite'
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Install poetry
      run: | 
        pipx install poetry==${{ inputs.poetry-version }}
        pipx inject poetry poetry-plugin-export
      shell: bash

    - name: Get Python version from pyproject.toml
      run: |
        VERSION=$(grep '^python =' pyproject.toml | sed 's/^python = "\(.*\)"/\1/')
        echo "PYTHON_VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'

    - run: poetry install
      shell: bash